### ISSUE TITLE
关于verity和verify

### ISSUE THREAD

**Issue by didikeke** [gwuhaolin/direct-alipay#2]
虽然这个项目是一年前的，但是也是可以用的。

只是不理解当时为何用verity现在又改了verify。
既然改了，那就 顺带 兼容下之前版本
exports.verify = verify;
exports.verity ＝ verify;
然后改下文档，最后npm升级发布到1.0.5？

想用下这个库，但是又不知道什么时候万一直接升级到1.0.5直接改了接口……

**Comment by gwuhaolin** [comment]
由于之前拼写错误发布出去了，
在这次提交中fix
https://github.com/gwuhaolin/direct-alipay/commit/7cf73e7e924f4f76796cf485764fcf7728e9d8da
不能容忍错误的保留，还是升级下改下自己的业务代码哈

**Comment by didikeke** [comment]
@gwuhaolin 因为你npm上一直是错误的1.0.4（现在也是），而且每周都有几个下载。如果你直接把修改后的1.0.5更新上去的话，不知道的人自动升级了包之后就会遇到bug（而且还是支付相关）。所以除非你升级版本号2.0.0，要么就得兼容下才好发布。 最好还是勇敢面对下曾经挖得坑，兼容下比较好。。。😄 就算master上没有黑历史了，版本历史里还在的呀。

**Comment by gwuhaolin** [comment]
public new npm version 1.1.0 in
https://github.com/gwuhaolin/direct-alipay/commit/5c1708f64cd6e0fe18847e9cc5dd5fbc9e7390d3

**Comment by didikeke** [comment]
升级到1.1.0应该是兼容升级的语义。 详见: http://semver.org/lang/zh-CN/
不过随便吧。反正我把版本固定了。。。

**Comment by didikeke** [comment]
@gwuhaolin 还有README哟

**Comment by gwuhaolin** [comment]
谢谢提醒，修改好了
