### ISSUE TITLE
老哥，请正确使用版本号

### ISSUE THREAD

**Issue by Debiancc** [gwuhaolin/direct-alipay#3]
同verify问题
如果坚持不兼容
烦劳major升级版本号
你这样会波及到使用到使用此npm的生产环境

https://docs.npmjs.com/cli/version

**Comment by gwuhaolin** [comment]
fix in
https://github.com/gwuhaolin/direct-alipay/commit/9b14427bc792567ab2e8312260f816c8c0ff8b6c
